namespace CodeGenNew.Core;

/// <summary> One line of meaning for each project setting key: what it does and what a blank value means. The Project Settings screen shows it beside the box, and a test keeps
/// it and Docs/Reference.md complete as keys are added. </summary>
public static class ProjectSettingsHints
{
    public static IReadOnlyDictionary<string, string> All { get; } = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
    {
        ["ViewNamespace"] = "blank = <ProjectName>.App.Views",
        ["ViewModelNamespace"] = "blank = <ProjectName>.App.ViewModels",
        ["ContextName"] = "blank = <ProjectName>Context",
        ["ContextNamespace"] = "blank = <ProjectName>.App.Data",
        ["ApiNamespace"] = "blank = <ProjectName>.ApiService.Apis",
        ["EnumNamespace"] = "blank = <ProjectName>.App.Enums",
        ["RepoNamespace"] = "blank = <ProjectName>.App.Repositories",
        ["EntityNamespace"] = "blank = <ProjectName>.App.Entities",
        ["MinYear"] = $"blank = {ProjectSettings.DefaultMinYear}",
        ["MaxYear"] = $"blank = {ProjectSettings.DefaultMaxYear}",
        ["CurrencyCode"] = "ISO currency code for money fields; blank = USD",
        ["ViewsFolder"] = "blank = the template's own folder",
        ["ViewModelsFolder"] = "blank = the template's own folder",
        ["Usings"] = "comma-separated namespaces every generated file should use",
        ["DetailMasterTables"] = "comma-separated table names whose Add/Edit dialog is a Detail-Master dialog (with child grids)",
        ["HiddenParents"] = "comma-separated tables whose foreign key columns the TypeScript forms hide",
        ["ModelFileOverrides"] = "Table=file pairs for model files not named after the table, e.g. DepartmentTeam=department,ProjectTask=project",
        ["BaseEntity"] = "base class of generated entities; blank = BaseEntity",
        ["BaseNameActiveEntity"] = "base class for Name + IsActive tables; blank = BaseNameActiveEntity",
        ["EnumTables"] = "comma-separated enum tables (no entity, repository or API); blank = decided from each table's shape",
        ["EnumNameSuffixes"] = "comma-separated name endings that mark an enum table; blank = Type, Types, Code, Codes, Status, Kind",
        ["EnumMaxRows"] = $"a lookup table with more rows than this is not an enum; blank = {ProjectSettings.DefaultEnumMaxRows}",
        ["NoLookupParents"] = "overrides EnumTables for this one question: tables whose foreign key is a number box, not a drop-down",
        ["NoRepositoryTables"] = "overrides EnumTables for this one question: tables that get no repository",
        ["NoApiTables"] = "overrides EnumTables for this one question: tables that get no API or TypeScript model/screen",
        ["NoNavigationTables"] = "overrides EnumTables for this one question: tables referenced without a navigation property",
        ["FakerNamespace"] = "the namespace of the Bogus fakers CS_Faker writes (default <ProjectName>.App.Fakers)",
        ["ApiDocs"] = "true: the plan also writes openapi.yaml (API_OpenApi) and the API serves it with a Swagger UI page at /docs",
        ["ApiFakers"] = "true: the plan also writes a Bogus fake-data generator per table (CS_Faker) and the generated project references Bogus",
        ["ApiHttp"] = "true: the plan also writes a .http request file per table (API_Http)",
        ["ProjectDocs"] = "true: the plan also writes a data dictionary page per table and the ER diagram (MD_DataDictionary, MD_Erd)",
        ["ApiValidation"] = "true: the plan also writes a FluentValidation validator per table (CS_Validator) and the create and update endpoints run them (400 with the messages)",
        ["AccessMode"] = "Routines or Ef: how search, sort, paging, clone and the junction editors reach the database. Ef uses LINQ over the context and needs no routine in the database; SQLite always uses it; blank = Routines",
        ["ValidatorNamespace"] = "the namespace of the FluentValidation validators CS_Validator writes (default <ProjectName>.App.Validators)",
        ["ErdTables"] = "comma-separated tables MD_Erd draws (Customer,SalesInvoice); empty: every table",
        ["DtoNamespace"] = "the namespace of the data-transfer classes and mappers (CS_Dto, CS_Mapper, CS_DataContractDto, CS_TypedDataRow, CS_SerializationDtos; default <ProjectName>.App.Dtos)",
        ["FSharpNamespace"] = "the namespace of the F# records FS_Entity and the Rop module FS_Rop write (default <ProjectName>.Domain)",
        ["ReplicationTargets"] = "SQL Server only: linked server and database each change is copied to, comma-separated (server1.Sales,server2.Sales); SP_ReplicationTriggers writes the triggers",
        ["KeySequenceTables"] = "SQL Server only: tables whose key comes from the key-sequence table instead of IDENTITY (Customer,Item); their insert routine calls GetNextID",
        ["KeySequenceTable"] = "the table the key sequence is kept in (default AutoInc)",
        ["BulkUpdateColumns"] = "SQL Server only: columns SP_BulkUpdate rewrites in every table that has one (Fnd,Acct)",
        ["BulkUpdateExpression"] = "what those columns are set to, {column} standing for the column (default UPPER({column}))",
        ["NonNegativeColumns"] = "comma-separated money columns that can never be negative (CreditLimit, or Item.Cost for one table): their number box gets a minimum of 0 (a CHECK range in the database does this without the list)",
        ["ApiFolder"] = "React / Angular folder for the api modules, relative to the source folder; blank = api",
        ["ModelsFolder"] = "React / Angular folder for the TypeScript models; blank = models",
        ["ServicesFolder"] = "Angular folder for the services; blank = services",
        ["ComponentsFolder"] = "React / Angular folder for the shared components and Angular screens; blank = components",
        ["PagesFolder"] = "React folder for the pages; blank = pages",
        ["AngularVersion"] = "major version of Angular, e.g. 22; blank = output that every version from 18 accepts",
        ["IgnoredColumns"] = "comma-separated columns to leave out (Tags, or Place.Location): a type CodeGenNew cannot map, such as an array or geometry",
        ["ListingName"] = "WinUI3_DirectoryListing: the class stem, e.g. Document (DocumentListPage); blank = Document",
        ["ListingFolder"] = "WinUI3_DirectoryListing: the folder whose files are listed (for example %LocalAppData%/Project/Name); blank = under LocalAppData",
        ["ListingPattern"] = "WinUI3_DirectoryListing: which files are listed; blank = *.*",
        ["Stacks"] = "stacks to generate: Api, WinUI3, React, Angular (comma-separated), e.g. Api,React",
        ["PlanAlso"] = "templates to run in a whole-project generate although their config leaves them out, e.g. SP_Insert,SP_Update",
        ["OutputApi"] = "folder of the API project under the output folder; blank = <ProjectName>.Api",
        ["OutputWinUI3"] = "folder of the WinUI3 app under the output folder; blank = <ProjectName>.App",
        ["OutputReact"] = "folder of the React app; blank = frontend",
        ["OutputAngular"] = "folder of the Angular app; blank = frontend",
        ["OutputSql"] = "folder of the generated SQL; blank = sql",
        ["AppNamespace"] = "root namespace of the WinUI3 app; blank = <ProjectName>.App",
        ["DatabaseProvider"] = "SqlServer, PostgreSql, MySql or Sqlite (appsettings.json and the package reference); blank = SqlServer",
        ["DatabaseServer"] = "server for appsettings.json; blank = localhost",
        ["DatabaseName"] = "database for appsettings.json (for SQLite the path of the database file); blank = the project name",
        ["DatabaseUser"] = "login for appsettings.json (never the password); blank = Windows authentication",
        ["ApiPort"] = "port the API listens on; blank = 5080",
        ["DevPort"] = "port of the front end's dev server; blank = 5173 (React) or 4200 (Angular)",
        ["ProjectTitle"] = "the web app's title; blank = the project name in words",
        ["BuildApi"] = "command that builds the API after a generate; blank = dotnet build -v q (none skips it)",
        ["BuildWinUI3"] = "command that builds the WinUI3 app after a generate; blank = dotnet build -v q",
        ["BuildReact"] = "command that builds the React app; blank = npm run build",
        ["BuildAngular"] = "command that builds the Angular app; blank = npm run build",
        ["TestApi"] = "command that tests the API; blank = no tests",
        ["TestWinUI3"] = "command that tests the WinUI3 app; blank = no tests",
        ["TestReact"] = "command that tests the React app; blank = npm test",
        ["TestAngular"] = "command that tests the Angular app; blank = npm test -- --watch=false",
        ["DbSetNames"] = "Plural = Customers, blank = the table name (Customer)",
        ["ProjectName"] = "the project's name (the file name of its .config); every blank namespace and folder is derived from it",
        ["NamingStyle"] = "AsIs (the database's names, the default) or Pascal (customer_item becomes CustomerItem; the SQL keeps the real names)",
        ["Acronyms"] = "comma-separated words the Pascal style keeps upper-case whole (PO,UPC,MSRP)",
        ["Screens"] = "comma-separated tables that get a screen, in menu order; blank = every table that has an API and a search, alphabetically",
        ["NoCloneTables"] = "comma-separated tables that get no Clone button although they could (Customer,SalesInvoice)",
        ["ChildGridTitles"] = "Parent.Child=Title pairs, comma-separated, for a child grid whose table name does not say what the rows mean (Customer.CustomerItem=Item Purchase History)"
    };
}
