<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\CodeGenNew.Core\CodeGenNew.Core.csproj" />
    <ProjectReference Include="..\CodeGenNew.Connections\CodeGenNew.Connections.csproj" />
    <ProjectReference Include="..\CodeGenNew.SchemaIntrospection\CodeGenNew.SchemaIntrospection.csproj" />
    <ProjectReference Include="..\CodeGenNew.TemplateEngine\CodeGenNew.TemplateEngine.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
